### ISSUE TITLE
How.

### ISSUE THREAD

**Issue by gurupras** [pkmngodev/Unknown6#5] opened 2016-08-05 04:07 UTC
First, great job on creating this repository for sharing information.

I'd like to know how you guys went about reverse engineering this. Given that this repository has been created for educational purposes, I'd really like to learn how to do something like this so I would be able to contribute as well.

**Comment by MaxLeiter** [comment] 2016-08-05 04:12
I recommend reading the Discord history (or just reading it from here on out). There is some information on the wiki; hopefully it can be updated more tomorrow when more developers are awake.

**Comment by firebolt55439** [comment] 2016-08-05 04:12
From what I understand, the devs here found the bridge between Unity and native Android code in the Pokemon GO APK (`libNianticPlugin.so` or such) and decompiled it through IDA. After that, they (fairly laboriously) determined what subroutines were responsible for the encryption and narrowed down the list to just two or three, then decompiled them as "messy" C, all of which are available on the wiki. All that remains is to figure out the new packet structure itself (e.g. what order the information comes in, how big each field is, what information is stored in what field, etc.) which will require some time. Kudos to the devs for all their hard work 👍 .

**Comment by gurupras** [comment] 2016-08-05 04:24
You're right. I should read through the discord history. I'm going to do that right now.

I know you guys are probably exhausted, but I really think that summarizing this would be a great way to get more people to contribute. It doesn't have to be as a comment to this 'issue'.  
I'm sure there are a lot of us dying to have an opportunity to learn from you guys so that we can contribute in the future.

- How was the debuggable version of the app created? (`apktool`?)
  - Was GDB used to set a breakpoint and dig into the call chain? If so, how?
  - Do you *all* use IDA to do the decompiling?
    - Is this different from objdump? What are some opensource alternatives to IDA? (`redare2`?)
  - How did you narrow this down to one or two?

One last (dumb) question I had was:  
If we knew it was `libNianticPlugin.so`, couldn't we have just linked it into programs and called the same function? I see that @firebolt55439 mentions that we do not know what the inputs are. Is this why we are unable to just link against the shared library and call the functions that we think are responsible for creating unknown6?

**Comment by xrobau** [comment] 2016-08-05 04:31
> couldn't we have just linked it into programs and called the same function?

Only if you were running that on an ARM CPU, assuming you knew what the inputs were.

**Comment by shark0der** [comment] 2016-08-05 04:36
There's no access to the discord `#api-debugging` channel history for now. Hope you'll make that public soon. Thanks for the great work!

**Comment by gurupras** [comment] 2016-08-05 04:37
I'm reading through it right now. I think its accessible.

**Comment by MaxLeiter** [comment] 2016-08-05 04:38
It should be public now, @shark0der. Pinging @keyphact to look into tomorrow

**Comment by wchill** [comment] 2016-08-05 04:46
> How was the debuggable version of the app created?

For Android apps, you can grab the smali disassembly by running it through APKTool, yes. A lot of times that's enough since most apps don't have any native code. However, in the case of Pokemon Go, since Unity compiles to native code using `il2cpp`, APKTool is not sufficient.

If you just want the native libraries being used, you can rename the extension to `.zip` then unzip it. This is because both APKs and IPAs (iOS) are just special ZIP files.

> Was GDB used to set a breakpoint and dig into the call chain? If so, how?

A lot of us used IDA (me simply because I'm more familiar with it due to having done x86 disassembly before), but Hopper or `radare2` can be used as well. A good disassembler will recover important things like function/symbol names, mark parts of the binary that are code and parts that are data, build a graph of which functions call what, etc. 

Once we have the list of symbol names, we can try breakpointing functions that appear to be interesting. On iOS, this is doable by copying `debug-server` to your device, using it to launch `pokemongo`, and then attaching to the debugging stub using `lldb`. (Supposedly, `frida` works as well, but I didn't try it.) On Android, you can use `ndk-gdb` or `frida`. Then we launch the debugger, find where the app is in memory and [calculate offsets for ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization), then set breakpoints on interesting functions. Once we do that, we can recover the call stack, examine/modify parts of memory, step through code as we please, etc. This is how we determined that `sub_87444` was legit: I breakpointed it and modified the data coming in and out of that function and grabbed the data sent for the API RPC call using Charles, comparing it with the modifications.

> Do you all use IDA to do the decompiling?

IDA technically doesn't decompile; that would be Hex-Rays Decompiler. Unfortunately there are not many good decompilers around, so we pretty much had to use that.

`objdump` is good for getting a disassembly of the binary, but it cannot decompile a program.

> How did you narrow this down to one or two?

Luck.

> If we knew it was libNianticPlugin.so, couldn't we have just linked it into programs and called the same function?

Two problems with this:

1. We don't know everything about what's being passed into `sub_87444`. This is what we're working on right now.

2. `libNianticPlugin.so` is compiled for ARM, so we cannot simply link it into programs because then the machines those programs would be running on would have to have ARM processors as well (unless you try and emulate or something stupid).

**Comment by shark0der** [comment] 2016-08-05 04:47
@MaxLeiter The channel itself is public. The channel **history** is not:

![image](https://cloud.githubusercontent.com/assets/528959/17426479/d721cc44-5ae0-11e6-9df4-2eb6d1b88b18.png)

**Comment by MaxLeiter** [comment] 2016-08-05 04:48
Make a separate issue please, @shark0der

**Comment by waryas** [comment] 2016-08-05 05:22
Actually you could use frida to bridge a native app and a arm app but that would require to know the input and have areal game running with the api.

**Comment by my2ndLanguage** [comment] 2016-08-05 05:38
absolutely stunning work.

**Comment by gandafor** [comment] 2016-08-05 05:40
Agreed! Stunning work!

**Comment by widnyana** [comment] 2016-08-05 06:20
@waryas does using raspberry pi count?

**Comment by wchill** [comment] 2016-08-05 06:22
@widnyana it won't run on a Raspberry Pi since you would need an ARMv7 or ARM64 CPU to run the code (RPi uses ARMv6).

**Comment by Bannz** [comment] 2016-08-05 06:32
what is it? anyone can tell me how make it is work?

**Comment by NoMotion** [comment] 2016-08-05 06:32
@wchill Different generations of RPi use different Architectures. RPi 3 Model B-2 is an ARMv7
It's [here]https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications) on the wiki

**Comment by soshimozi** [comment] 2016-08-05 06:38
RPi 3 is 64 bit CPU architecture.  I don't thing Raspbian has been ported to 64 bit yet though, so no OS at 64 bit, but the CPU is 64 bit.

**Comment by wchill** [comment] 2016-08-05 06:48
Ah, yes, you are correct. If Raspbian is compiled for ARMv7 though then it could work.

**Comment by NoMotion** [comment] 2016-08-05 06:51
@wchill is 64-bit os required to compile the source tho like @soshimozi says?

**Comment by soshimozi** [comment] 2016-08-05 06:52
@NoMotion it's not just the OS, but you need a 64 bit kernel and the company has already said that it is a low priority at this point.

**Comment by airjesse123** [comment] 2016-08-05 06:57
Are there already folks preparing for pull requests on AHAAAAAAA's PokemonGo-Map? Or should we start working on that.

**Comment by NoMotion** [comment] 2016-08-05 07:09
@airjesse123 Is there a fix to PR??

**Comment by pasky** [comment] 2016-08-05 10:19
> couldn't we have just linked it into programs and called the same function?

This isn't such a silly idea! You could easily run the ARM emulation in qemu, that's not the problem. The issue is, you'd need to figure out the API of libNianticPlugin.so, which would be about as tricky as figuring out the sub_87444 inputs and mostly a separate, disconnected effort. Maybe someone is trying to do it.  It's a less flexible approach, though.

Another point re why this journey may yet take a while: Even when the inputs are figured out, they include various sensor data which need to look reasonably realistic. Even a static phone sees some slight jitter there, so modelling that will be important - that's the whole point of the anti-cheat protection being so convoluted, at least I'd be seriously disappointed in Niantic if they didn't do that.  And a moving phone, e.g. when you want to jump around for mapping, needs to send realistic-looking sensor data, which is a whole another different level; some machine learning graphical models trained on crowdsourced movement data will be required to accurately model that, I think (as that's likely to be what they use on the other side to).

**Comment by D4D3Z** [comment] 2016-08-05 10:21
Was trying all night FCuking The UNKNOWN6, but, a lot of question are inside me... 
Well get some rest and try again later.
Teh massive works every Dev are doing is priceless <3

**Comment by EdenGottlieb** [comment] 2016-08-05 11:08
@airjesse123
 PokemonGo-Map relies on PGoAPI for connecting to Niantic's servers. Its copy of the API is maintained with git and updated each time the program builds, so once PGoAPI is fixed PokenonGo-Map should be fixed as well.
(Actually its currently fixed on a commit (the last one) but that can be changed in a heartbeat)

**Comment by dabnoj** [comment] 2016-08-05 11:32
@pasky so how can Nox send those "Realistic" sensor datas?

**Comment by dverlik** [comment] 2016-08-05 12:24
the code in APK sends data to libNianticPlugin.so, amirite? Why isn't in possible to repack the APK and recompile the libNianticPlugin.so while modifying their internal code to write a detailed log what is transferred and what happens to it?

**Comment by NotBela** [comment] 2016-08-05 12:26
Blame me if im wrong, but you can just Log stuff. Nativ Code means, that you will only see Assembly parts, no Var Names, No Function etc. You can easly see all the stuff that is happening, but you have to understand it.

**Comment by dverlik** [comment] 2016-08-05 12:33
@NotBela ow, that makes sense, although i still don's understand why we can't just intercept the data between APK and the native part and generate our 'realistic' data and send it to the native lib. Is it because the lib somehow communicates with something apart the APK?

**Comment by BAndysc** [comment] 2016-08-05 12:46
Everything is happening in the native code, which has all function names, variables cut away that's why it takes time to understand it and place where unknown6 is generated

**Comment by thargor** [comment] 2016-08-05 12:49
What the native part gets from apk is Sensor data and communication
packages. We already have traces of communication between apk and lib. We
need to know how the lib creates/signs these messages with our custom data.
The current work is to determine what kind of data is signed through the
algorithm.

It is not trivial to determine what binary numbers mean. Depending on its
position the hex code 0xfe could mean your mobile phone is in standby mode
or a identify a certain pokemon. You need to do data flow analysis through
a lot of optimized assembly code to find the origin and therefore meaning.
(or be good at guessing/interpreting well known formats or encodings)

dverlik <notifications@github.com> schrieb am Fr., 5. Aug. 2016, 14:33:

**Comment by NotBela** [comment] 2016-08-05 12:53
@dverlik For dummies: It sounds like the real magic is completly taking place in native code. The "connection" between the native an non nativ part is just for passing sensor data and sending events to the ui. The whole encoding, decoding, and Network Connection is done in Native Code.

**Comment by dverlik** [comment] 2016-08-05 12:58
@NotBela i know that - and being the native part a blackbox is okay as far as an emulated user sends his data into that blackbox. You said the native code recieves sensor data and UI commands - so what is the main problem in making a program that emulates the APK java code part, passing to the native part the sensor/UI data it wants to recieve?

**Comment by pasky** [comment] 2016-08-05 13:46
@dverlik Try it and see! I think such an alternative parallel effort would be welcome. You need to figure out the API of the library.

**Comment by NotBela** [comment] 2016-08-05 14:06
Nearly the whole App is a black box. Only the the device specific things like Sensors or Engine are decompileable. The whole magic happens inside the unity scripts - which are sadly in native code.

**Comment by dverlik** [comment] 2016-08-05 14:12
@NotBela @pasky Anyways, i will look into it, i am still sure it can be solved that way (even if it will come to have an anroid emulator with a program sending ui activities to the PGo app)

**Comment by NotBela** [comment] 2016-08-05 14:17
Ye, just do it :D Feel free to send me updates about your progress via email or on the discord.

**Comment by salvprest** [comment] 2016-08-05 14:30
@dverlik  the app now support x86 cpu, so there must be a x86 version of libNianticPlugin.so

**Comment by dverlik** [comment] 2016-08-05 14:32
@salvprest Thanks for the info

**Comment by soshimozi** [comment] 2016-08-05 17:32
@salvprest if it's x86 are you talking windows PE format or ABI ELF format on x86 platform?

**Comment by shark0der** [comment] 2016-08-05 17:39
@dverlik not sure though. I couldn't find an apk for x86 - I only found a site claiming it has the apk but the link was to arm.
@soshimozi that'd be ELF, since it's for asus zenfone which runs android.

**Comment by soshimozi** [comment] 2016-08-05 18:18
@shark0der Yeah, I guess I should have just asked the platform.  I haven't done any windows phone programming since early on, so I'm not entirely sure what the platform is supporting right now.  If it's android then it's definitely ABI ELF.

**Comment by Auth0x** [comment] 2016-08-05 19:17
@soshimozi Yep, it's ARM x86-64...so it doesn't change for the better, right?

**Comment by wchill** [comment] 2016-08-05 19:47
@soshimozi @Auth0x ARM x86 isn't a thing.

**Comment by firebolt55439** [comment] 2016-08-05 22:08
Quick question - what function does `Signature.proto` serve? For example, does it represent the structure of the unknown6 field or is it unrelated to the encryption entirely? I'm somewhat confused about what all the decompiled C code does in the protocol.

**Comment by trisk** [comment] 2016-08-05 22:13
Signature.proto is the description of the protobuf that is the input to the main hash function which yields the Unknown6 blob.

**Comment by firebolt55439** [comment] 2016-08-05 22:38
@trisk I see. So that's why we're trying to decrypt the signature now - makes sense :)

**Comment by yaonatanz** [comment] 2016-08-06 00:45
Does anyone have documented information  about the so? I can look at this tommorw...  I might be helful

**Closed** 2016-08-06 00:46 UTC
Labels: question
